### ISSUE TITLE
[Question] Can i port this mod to both 1.19.2 & 1.20.1?

### ISSUE THREAD

**Issue by min2222** [Mrbt0907/The-Mo-Withers-Mod#1]
hello, i'm really glad that this mod become open source.
i'm very experienced with porting mods (specifically 1.12.2 -> 1.19.2 and 1.19.2 -> 1.20.1)
so if you don't mind, can i port this mod to both 1.19.2 & 1.20.1?
i will not upload port to anywhere else, and you can just upload the port to original curseforge page.
you don't even need to credit me.

**Comment by min2222** [comment]
if 1.12.2 version isn't finished yet, i can wait until done.

**Comment by Mrbt0907** [comment]
As I clarified in my initial announcement, this mod is not open sourced, and therefore you are not allowed to port this to any version.

The code is public so people can contribute with pull requests, or just to simply allow other mod creators to add compatibility for his various mods like this one easily.
